# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods
    increment_build_number(xcodeproj: "VeraSDKDemo.xcodeproj")
    add_badge(shield: "VeraSDK-#{read_podspec(path: "../VeraSDK.podspec")['version']}-blue", no_badge: true)
    match(readonly: true, type: "appstore")
    build_app(workspace: "VeraSDKDemo.xcworkspace", scheme: "VeraSDKDemo")
    upload_to_testflight
  end
end
