# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'VeraSDKExample-CP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VeraSDK', :path => '../..'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/OAuth'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/Google'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
